version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - mikrotik-db-data:/app/data
    restart: always

volumes:
  mikrotik-db-data:
    driver: local
